"""empty message

Revision ID: 096437c4be23
Revises: b42987a440d7
Create Date: 2020-02-04 06:03:56.972260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096437c4be23'
down_revision = 'b42987a440d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre_venue',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre_venue')
    # ### end Alembic commands ###
