"""empty message

Revision ID: 72dd13f248de
Revises: 5f81d1bd5864
Create Date: 2020-02-03 06:50:36.469297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dd13f248de'
down_revision = '5f81d1bd5864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('state_id', sa.Integer(), nullable=True))
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'Artist', 'city', ['city_id'], ['id'])
    op.create_foreign_key(None, 'Artist', 'state', ['state_id'], ['id'])
    op.drop_column('Artist', 'city')
    op.drop_column('Artist', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'state_id')
    op.drop_column('Artist', 'seeking_venues')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'city_id')
    # ### end Alembic commands ###
