"""empty message

Revision ID: 905cd34b9557
Revises: 448dab54dd23
Create Date: 2020-02-03 17:16:56.508946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905cd34b9557'
down_revision = '448dab54dd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genre_artist',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    op.alter_column('Artist', 'seeking_venues',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venues',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('genre_artist')
    op.drop_table('genre')
    # ### end Alembic commands ###
