"""empty message

Revision ID: d76dbd933789
Revises: 9212b17f9060
Create Date: 2020-01-30 12:52:35.722537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd76dbd933789'
down_revision = '9212b17f9060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Venue', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('Venue', sa.Column('state_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'city', ['city_id'], ['id'])
    op.create_foreign_key(None, 'Venue', 'state', ['state_id'], ['id'])
    op.drop_column('Venue', 'city')
    op.drop_column('Venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'state_id')
    op.drop_column('Venue', 'city_id')
    op.drop_table('city')
    op.drop_table('state')
    # ### end Alembic commands ###
